//! Known CSS identifiers for validation rules.
//!
//! All arrays are sorted alphabetically for binary search.

use gale_css_parser::Syntax;

// Lookup helpers — case-insensitive binary search.

/// Case-insensitive binary search over a sorted, lowercase table.
fn lookup(haystack: &[&str], needle: &str) -> bool {
  let lower = needle.to_ascii_lowercase();
  haystack.binary_search(&lower.as_str()).is_ok()
}

/// Whether `name` is a property the installed Stylelint knows.
pub fn is_known_property(name: &str) -> bool {
  is_known_property_for(name, crate::stylelint_version::stylelint_major_version())
}

/// Whether Stylelint of major version `stylelint_major` knows the property
/// `name`: the two versions draw on different property data.
pub fn is_known_property_for(name: &str, stylelint_major: u32) -> bool {
  lookup(KNOWN_PROPERTIES, name)
    || if stylelint_major >= 17 {
      lookup(STYLELINT_17_PROPERTIES, name)
    } else {
      lookup(STYLELINT_16_PROPERTIES, name)
    }
}

/// Whether `name` is a standard CSS at-rule (without the `@`).
pub fn is_known_at_rule(name: &str) -> bool {
  lookup(KNOWN_AT_RULES, name)
}

/// Returns `true` when the at-rule name is valid for the given syntax.
///
/// - `Syntax::Css` — only standard CSS at-rules.
/// - `Syntax::Scss` / `Syntax::Sass` — CSS at-rules plus SCSS-specific ones.
/// - `Syntax::Less` — CSS at-rules plus Less-specific ones.
pub fn is_known_at_rule_for_syntax(name: &str, syntax: Syntax) -> bool {
  if is_known_at_rule(name) {
    return true;
  }
  match syntax {
    Syntax::Scss | Syntax::Sass => lookup(KNOWN_SCSS_AT_RULES, name),
    Syntax::Less => lookup(KNOWN_LESS_AT_RULES, name),
    Syntax::Css => false,
  }
}

/// Whether `name` is a standard CSS pseudo-class (without the `:`).
pub fn is_known_pseudo_class(name: &str) -> bool {
  lookup(KNOWN_PSEUDO_CLASSES, name)
}

/// Whether `name` is a standard CSS pseudo-element (without the `::`).
pub fn is_known_pseudo_element(name: &str) -> bool {
  lookup(KNOWN_PSEUDO_ELEMENTS, name)
}

/// Whether `name` is a standard CSS unit.
pub fn is_known_unit(name: &str) -> bool {
  lookup(KNOWN_UNITS, name)
}

/// Whether `name` is a standard CSS media feature.
pub fn is_known_media_feature(name: &str) -> bool {
  lookup(KNOWN_MEDIA_FEATURES, name)
}

/// Whether `name` is a standard HTML element name.
pub fn is_known_html_element(name: &str) -> bool {
  lookup(KNOWN_HTML_ELEMENTS, name)
}

/// Whether `name` is an HTML element Stylelint recognises that has not yet
/// reached the standard set, such as `selectlist` or `fencedframe`.
pub fn is_experimental_html_element(name: &str) -> bool {
  lookup(EXPERIMENTAL_HTML_ELEMENTS, name)
}

// ---------------------------------------------------------------------------
// CSS Properties (sorted)
//
// Stylelint 16 knows the properties in `known-css-properties` (0.37);
// Stylelint 17 asks the css-tree lexer, then its `previouslyKnownProperties`
// list.  `KNOWN_PROPERTIES` holds the unprefixed names both know, and the
// two lists after it the names only one of them knows.
// ---------------------------------------------------------------------------

static KNOWN_PROPERTIES: &[&str] = &[
  "accelerator",
  "accent-color",
  "align-content",
  "align-items",
  "align-self",
  "alignment-baseline",
  "all",
  "alt",
  "anchor-name",
  "anchor-scope",
  "animation",
  "animation-composition",
  "animation-delay",
  "animation-direction",
  "animation-duration",
  "animation-fill-mode",
  "animation-iteration-count",
  "animation-name",
  "animation-play-state",
  "animation-range",
  "animation-range-end",
  "animation-range-start",
  "animation-timeline",
  "animation-timing-function",
  "animation-trigger",
  "animation-trigger-behavior",
  "animation-trigger-exit-range",
  "animation-trigger-exit-range-end",
  "animation-trigger-exit-range-start",
  "animation-trigger-range",
  "animation-trigger-range-end",
  "animation-trigger-range-start",
  "animation-trigger-timeline",
  "app-region",
  "appearance",
  "aspect-ratio",
  "audio-level",
  "backdrop-filter",
  "backface-visibility",
  "background",
  "background-attachment",
  "background-blend-mode",
  "background-clip",
  "background-color",
  "background-image",
  "background-origin",
  "background-position",
  "background-position-x",
  "background-position-y",
  "background-repeat",
  "background-repeat-x",
  "background-repeat-y",
  "background-size",
  "baseline-shift",
  "baseline-source",
  "behavior",
  "block-ellipsis",
  "block-size",
  "block-step",
  "block-step-align",
  "block-step-insert",
  "block-step-round",
  "block-step-size",
  "bookmark-label",
  "bookmark-level",
  "bookmark-state",
  "border",
  "border-block",
  "border-block-color",
  "border-block-end",
  "border-block-end-color",
  "border-block-end-style",
  "border-block-end-width",
  "border-block-start",
  "border-block-start-color",
  "border-block-start-style",
  "border-block-start-width",
  "border-block-style",
  "border-block-width",
  "border-bottom",
  "border-bottom-color",
  "border-bottom-left-radius",
  "border-bottom-right-radius",
  "border-bottom-style",
  "border-bottom-width",
  "border-boundary",
  "border-collapse",
  "border-color",
  "border-end-end-radius",
  "border-end-start-radius",
  "border-image",
  "border-image-outset",
  "border-image-repeat",
  "border-image-slice",
  "border-image-source",
  "border-image-width",
  "border-inline",
  "border-inline-color",
  "border-inline-end",
  "border-inline-end-color",
  "border-inline-end-style",
  "border-inline-end-width",
  "border-inline-start",
  "border-inline-start-color",
  "border-inline-start-style",
  "border-inline-start-width",
  "border-inline-style",
  "border-inline-width",
  "border-left",
  "border-left-color",
  "border-left-style",
  "border-left-width",
  "border-radius",
  "border-right",
  "border-right-color",
  "border-right-style",
  "border-right-width",
  "border-spacing",
  "border-start-end-radius",
  "border-start-start-radius",
  "border-style",
  "border-top",
  "border-top-color",
  "border-top-left-radius",
  "border-top-right-radius",
  "border-top-style",
  "border-top-width",
  "border-width",
  "bottom",
  "box-decoration-break",
  "box-shadow",
  "box-sizing",
  "box-snap",
  "break-after",
  "break-before",
  "break-inside",
  "buffered-rendering",
  "caption-side",
  "caret",
  "caret-animation",
  "caret-color",
  "caret-shape",
  "chains",
  "clear",
  "clip",
  "clip-path",
  "clip-rule",
  "color",
  "color-adjust",
  "color-interpolation",
  "color-interpolation-filters",
  "color-profile",
  "color-rendering",
  "color-scheme",
  "column-count",
  "column-fill",
  "column-gap",
  "column-height",
  "column-progression",
  "column-rule",
  "column-rule-break",
  "column-rule-color",
  "column-rule-outset",
  "column-rule-style",
  "column-rule-width",
  "column-span",
  "column-width",
  "column-wrap",
  "columns",
  "contain",
  "contain-intrinsic-block-size",
  "contain-intrinsic-height",
  "contain-intrinsic-inline-size",
  "contain-intrinsic-size",
  "contain-intrinsic-width",
  "container",
  "container-name",
  "container-type",
  "content",
  "content-visibility",
  "continue",
  "counter-increment",
  "counter-reset",
  "counter-set",
  "cue",
  "cue-after",
  "cue-before",
  "cursor",
  "cx",
  "cy",
  "d",
  "direction",
  "display",
  "display-align",
  "dominant-baseline",
  "dynamic-range-limit",
  "elevation",
  "empty-cells",
  "enable-background",
  "epub-caption-side",
  "epub-hyphens",
  "epub-text-combine",
  "epub-text-emphasis",
  "epub-text-emphasis-color",
  "epub-text-emphasis-style",
  "epub-text-orientation",
  "epub-text-transform",
  "epub-word-break",
  "epub-writing-mode",
  "field-sizing",
  "fill",
  "fill-break",
  "fill-color",
  "fill-image",
  "fill-opacity",
  "fill-origin",
  "fill-position",
  "fill-repeat",
  "fill-rule",
  "fill-size",
  "filter",
  "flex",
  "flex-basis",
  "flex-direction",
  "flex-flow",
  "flex-grow",
  "flex-shrink",
  "flex-wrap",
  "float",
  "float-defer",
  "float-offset",
  "float-reference",
  "flood-color",
  "flood-opacity",
  "flow",
  "flow-from",
  "flow-into",
  "font",
  "font-family",
  "font-feature-settings",
  "font-kerning",
  "font-language-override",
  "font-optical-sizing",
  "font-palette",
  "font-size",
  "font-size-adjust",
  "font-stretch",
  "font-style",
  "font-synthesis",
  "font-synthesis-position",
  "font-synthesis-small-caps",
  "font-synthesis-style",
  "font-synthesis-weight",
  "font-variant",
  "font-variant-alternates",
  "font-variant-caps",
  "font-variant-east-asian",
  "font-variant-emoji",
  "font-variant-ligatures",
  "font-variant-numeric",
  "font-variant-position",
  "font-variation-settings",
  "font-weight",
  "font-width",
  "footnote-display",
  "footnote-policy",
  "forced-color-adjust",
  "gap",
  "glyph-orientation-horizontal",
  "glyph-orientation-vertical",
  "grid",
  "grid-area",
  "grid-auto-columns",
  "grid-auto-flow",
  "grid-auto-rows",
  "grid-column",
  "grid-column-end",
  "grid-column-gap",
  "grid-column-start",
  "grid-gap",
  "grid-row",
  "grid-row-end",
  "grid-row-gap",
  "grid-row-start",
  "grid-template",
  "grid-template-areas",
  "grid-template-columns",
  "grid-template-rows",
  "hanging-punctuation",
  "height",
  "hyphenate-character",
  "hyphenate-limit-chars",
  "hyphenate-limit-last",
  "hyphenate-limit-lines",
  "hyphenate-limit-zone",
  "hyphens",
  "image-orientation",
  "image-rendering",
  "image-resolution",
  "ime-mode",
  "initial-letter",
  "initial-letter-align",
  "initial-letter-wrap",
  "inline-size",
  "inline-sizing",
  "input-format",
  "input-security",
  "inset",
  "inset-area",
  "inset-block",
  "inset-block-end",
  "inset-block-start",
  "inset-inline",
  "inset-inline-end",
  "inset-inline-start",
  "interactivity",
  "interpolate-size",
  "isolation",
  "item-slack",
  "justify-content",
  "justify-items",
  "justify-self",
  "kerning",
  "layout-flow",
  "layout-grid",
  "layout-grid-char",
  "layout-grid-line",
  "layout-grid-mode",
  "layout-grid-type",
  "left",
  "letter-spacing",
  "lighting-color",
  "line-break",
  "line-clamp",
  "line-fit-edge",
  "line-grid",
  "line-height",
  "line-height-step",
  "line-increment",
  "line-padding",
  "line-snap",
  "list-style",
  "list-style-image",
  "list-style-position",
  "list-style-type",
  "margin",
  "margin-block",
  "margin-block-end",
  "margin-block-start",
  "margin-bottom",
  "margin-break",
  "margin-inline",
  "margin-inline-end",
  "margin-inline-start",
  "margin-left",
  "margin-right",
  "margin-top",
  "margin-trim",
  "marker",
  "marker-end",
  "marker-knockout-left",
  "marker-knockout-right",
  "marker-mid",
  "marker-offset",
  "marker-pattern",
  "marker-segment",
  "marker-side",
  "marker-start",
  "mask",
  "mask-border",
  "mask-border-mode",
  "mask-border-outset",
  "mask-border-repeat",
  "mask-border-slice",
  "mask-border-source",
  "mask-border-width",
  "mask-clip",
  "mask-composite",
  "mask-image",
  "mask-mode",
  "mask-origin",
  "mask-position",
  "mask-position-x",
  "mask-position-y",
  "mask-repeat",
  "mask-size",
  "mask-source-type",
  "mask-type",
  "math-depth",
  "math-shift",
  "math-style",
  "max-block-size",
  "max-height",
  "max-inline-size",
  "max-lines",
  "max-width",
  "min-block-size",
  "min-height",
  "min-inline-size",
  "min-intrinsic-sizing",
  "min-width",
  "mix-blend-mode",
  "motion",
  "motion-offset",
  "motion-path",
  "motion-rotation",
  "nav-down",
  "nav-index",
  "nav-left",
  "nav-right",
  "nav-up",
  "navigation",
  "object-fit",
  "object-position",
  "object-view-box",
  "offset",
  "offset-anchor",
  "offset-block-end",
  "offset-block-start",
  "offset-distance",
  "offset-inline-end",
  "offset-inline-start",
  "offset-path",
  "offset-position",
  "offset-rotate",
  "offset-rotation",
  "opacity",
  "order",
  "orphans",
  "outline",
  "outline-color",
  "outline-offset",
  "outline-style",
  "outline-width",
  "overflow",
  "overflow-anchor",
  "overflow-block",
  "overflow-clip-margin",
  "overflow-clip-margin-block",
  "overflow-clip-margin-block-end",
  "overflow-clip-margin-block-start",
  "overflow-clip-margin-bottom",
  "overflow-clip-margin-inline",
  "overflow-clip-margin-inline-end",
  "overflow-clip-margin-inline-start",
  "overflow-clip-margin-left",
  "overflow-clip-margin-right",
  "overflow-clip-margin-top",
  "overflow-inline",
  "overflow-wrap",
  "overflow-x",
  "overflow-y",
  "overlay",
  "overscroll-behavior",
  "overscroll-behavior-block",
  "overscroll-behavior-inline",
  "overscroll-behavior-x",
  "overscroll-behavior-y",
  "padding",
  "padding-block",
  "padding-block-end",
  "padding-block-start",
  "padding-bottom",
  "padding-inline",
  "padding-inline-end",
  "padding-inline-start",
  "padding-left",
  "padding-right",
  "padding-top",
  "page",
  "page-break-after",
  "page-break-before",
  "page-break-inside",
  "paint-order",
  "pause",
  "pause-after",
  "pause-before",
  "pen-action",
  "perspective",
  "perspective-origin",
  "perspective-origin-x",
  "perspective-origin-y",
  "pitch",
  "pitch-range",
  "place-content",
  "place-items",
  "place-self",
  "play-during",
  "pointer-events",
  "position",
  "position-anchor",
  "position-area",
  "position-try",
  "position-try-fallbacks",
  "position-try-options",
  "position-try-order",
  "position-visibility",
  "print-color-adjust",
  "property-name",
  "quotes",
  "r",
  "reading-flow",
  "reading-order",
  "region-fragment",
  "resize",
  "rest",
  "rest-after",
  "rest-before",
  "richness",
  "right",
  "rotate",
  "row-gap",
  "row-rule",
  "row-rule-break",
  "row-rule-color",
  "row-rule-outset",
  "row-rule-style",
  "row-rule-width",
  "ruby-align",
  "ruby-merge",
  "ruby-overhang",
  "ruby-position",
  "rule",
  "rule-break",
  "rule-color",
  "rule-outset",
  "rule-paint-order",
  "rule-style",
  "rule-width",
  "running",
  "rx",
  "ry",
  "scale",
  "scroll-behavior",
  "scroll-initial-target",
  "scroll-margin",
  "scroll-margin-block",
  "scroll-margin-block-end",
  "scroll-margin-block-start",
  "scroll-margin-bottom",
  "scroll-margin-inline",
  "scroll-margin-inline-end",
  "scroll-margin-inline-start",
  "scroll-margin-left",
  "scroll-margin-right",
  "scroll-margin-top",
  "scroll-marker-group",
  "scroll-padding",
  "scroll-padding-block",
  "scroll-padding-block-end",
  "scroll-padding-block-start",
  "scroll-padding-bottom",
  "scroll-padding-inline",
  "scroll-padding-inline-end",
  "scroll-padding-inline-start",
  "scroll-padding-left",
  "scroll-padding-right",
  "scroll-padding-top",
  "scroll-snap-align",
  "scroll-snap-coordinate",
  "scroll-snap-destination",
  "scroll-snap-margin",
  "scroll-snap-margin-bottom",
  "scroll-snap-margin-left",
  "scroll-snap-margin-right",
  "scroll-snap-margin-top",
  "scroll-snap-points-x",
  "scroll-snap-points-y",
  "scroll-snap-stop",
  "scroll-snap-type",
  "scroll-snap-type-x",
  "scroll-snap-type-y",
  "scroll-start-target",
  "scroll-target-group",
  "scroll-timeline",
  "scroll-timeline-axis",
  "scroll-timeline-name",
  "scrollbar-arrow-color",
  "scrollbar-base-color",
  "scrollbar-color",
  "scrollbar-dark-shadow-color",
  "scrollbar-darkshadow-color",
  "scrollbar-face-color",
  "scrollbar-gutter",
  "scrollbar-highlight-color",
  "scrollbar-shadow-color",
  "scrollbar-track-color",
  "scrollbar-width",
  "scrollbar3d-light-color",
  "scrollbar3dlight-color",
  "shape-image-threshold",
  "shape-inside",
  "shape-margin",
  "shape-outside",
  "shape-rendering",
  "slider-orientation",
  "snap-height",
  "solid-color",
  "solid-opacity",
  "spatial-navigation-action",
  "spatial-navigation-contain",
  "spatial-navigation-function",
  "speak",
  "speak-as",
  "speak-header",
  "speak-numeral",
  "speak-punctuation",
  "speech-rate",
  "stop-color",
  "stop-opacity",
  "stress",
  "string-set",
  "stroke",
  "stroke-align",
  "stroke-alignment",
  "stroke-break",
  "stroke-color",
  "stroke-dash-corner",
  "stroke-dash-justify",
  "stroke-dashadjust",
  "stroke-dasharray",
  "stroke-dashcorner",
  "stroke-dashoffset",
  "stroke-image",
  "stroke-linecap",
  "stroke-linejoin",
  "stroke-miterlimit",
  "stroke-opacity",
  "stroke-origin",
  "stroke-position",
  "stroke-repeat",
  "stroke-size",
  "stroke-width",
  "supported-color-schemes",
  "tab-size",
  "table-layout",
  "text-align",
  "text-align-all",
  "text-align-last",
  "text-anchor",
  "text-autospace",
  "text-box",
  "text-box-edge",
  "text-box-trim",
  "text-combine-upright",
  "text-decoration",
  "text-decoration-blink",
  "text-decoration-color",
  "text-decoration-line",
  "text-decoration-line-through",
  "text-decoration-none",
  "text-decoration-overline",
  "text-decoration-skip",
  "text-decoration-skip-box",
  "text-decoration-skip-ink",
  "text-decoration-skip-inset",
  "text-decoration-skip-self",
  "text-decoration-skip-spaces",
  "text-decoration-style",
  "text-decoration-thickness",
  "text-decoration-trim",
  "text-decoration-underline",
  "text-emphasis",
  "text-emphasis-color",
  "text-emphasis-position",
  "text-emphasis-skip",
  "text-emphasis-style",
  "text-group-align",
  "text-indent",
  "text-justify",
  "text-justify-trim",
  "text-kashida",
  "text-kashida-space",
  "text-line-through",
  "text-line-through-color",
  "text-line-through-mode",
  "text-line-through-style",
  "text-line-through-width",
  "text-orientation",
  "text-overflow",
  "text-overline",
  "text-overline-color",
  "text-overline-mode",
  "text-overline-style",
  "text-overline-width",
  "text-rendering",
  "text-shadow",
  "text-size-adjust",
  "text-spacing",
  "text-spacing-trim",
  "text-transform",
  "text-underline",
  "text-underline-color",
  "text-underline-mode",
  "text-underline-offset",
  "text-underline-position",
  "text-underline-style",
  "text-underline-width",
  "text-wrap",
  "text-wrap-mode",
  "text-wrap-style",
  "timeline-scope",
  "top",
  "touch-action",
  "touch-action-delay",
  "transform",
  "transform-box",
  "transform-origin",
  "transform-origin-x",
  "transform-origin-y",
  "transform-origin-z",
  "transform-style",
  "transition",
  "transition-behavior",
  "transition-delay",
  "transition-duration",
  "transition-property",
  "transition-timing-function",
  "translate",
  "uc-alt-skin",
  "uc-skin",
  "unicode-bidi",
  "user-select",
  "vector-effect",
  "vertical-align",
  "view-timeline",
  "view-timeline-axis",
  "view-timeline-inset",
  "view-timeline-name",
  "view-transition-class",
  "view-transition-group",
  "view-transition-name",
  "viewport-fill",
  "viewport-fill-opacity",
  "visibility",
  "voice-balance",
  "voice-duration",
  "voice-family",
  "voice-pitch",
  "voice-range",
  "voice-rate",
  "voice-stress",
  "voice-volume",
  "volume",
  "white-space",
  "white-space-collapse",
  "white-space-trim",
  "widows",
  "width",
  "will-change",
  "word-break",
  "word-space-transform",
  "word-spacing",
  "word-wrap",
  "wrap-after",
  "wrap-before",
  "wrap-flow",
  "wrap-inside",
  "wrap-through",
  "writing-mode",
  "x",
  "y",
  "z-index",
  "zoom",
];

/// Properties Stylelint 17 knows (css-tree or `previouslyKnownProperties`)
/// that `known-css-properties`, and so Stylelint 16, does not.
static STYLELINT_17_PROPERTIES: &[&str] = &[
  "align-tracks",
  "animation-range-center",
  "background-position-block",
  "background-position-inline",
  "background-repeat-block",
  "background-repeat-inline",
  "background-tbd",
  "border-block-clip",
  "border-block-end-clip",
  "border-block-end-radius",
  "border-block-start-clip",
  "border-block-start-radius",
  "border-bottom-clip",
  "border-bottom-radius",
  "border-clip",
  "border-inline-clip",
  "border-inline-end-clip",
  "border-inline-end-radius",
  "border-inline-start-clip",
  "border-inline-start-radius",
  "border-left-clip",
  "border-left-radius",
  "border-limit",
  "border-right-clip",
  "border-right-radius",
  "border-shape",
  "border-top-clip",
  "border-top-radius",
  "box-align",
  "box-direction",
  "box-flex",
  "box-flex-group",
  "box-lines",
  "box-ordinal-group",
  "box-orient",
  "box-pack",
  "box-shadow-blur",
  "box-shadow-color",
  "box-shadow-offset",
  "box-shadow-position",
  "box-shadow-spread",
  "column-rule-inset",
  "column-rule-inset-cap",
  "column-rule-inset-cap-end",
  "column-rule-inset-cap-start",
  "column-rule-inset-end",
  "column-rule-inset-junction",
  "column-rule-inset-junction-end",
  "column-rule-inset-junction-start",
  "column-rule-inset-start",
  "column-rule-visibility-items",
  "copy-into",
  "corner",
  "corner-block-end",
  "corner-block-end-shape",
  "corner-block-start",
  "corner-block-start-shape",
  "corner-bottom",
  "corner-bottom-left",
  "corner-bottom-left-shape",
  "corner-bottom-right",
  "corner-bottom-right-shape",
  "corner-bottom-shape",
  "corner-end-end",
  "corner-end-end-shape",
  "corner-end-start",
  "corner-end-start-shape",
  "corner-inline-end",
  "corner-inline-end-shape",
  "corner-inline-start",
  "corner-inline-start-shape",
  "corner-left",
  "corner-left-shape",
  "corner-right",
  "corner-right-shape",
  "corner-shape",
  "corner-start-end",
  "corner-start-end-shape",
  "corner-start-start",
  "corner-start-start-shape",
  "corner-top",
  "corner-top-left",
  "corner-top-left-shape",
  "corner-top-right",
  "corner-top-right-shape",
  "corner-top-shape",
  "event-trigger",
  "event-trigger-name",
  "event-trigger-source",
  "flex-line-count",
  "flow-tolerance",
  "font-smooth",
  "frame-sizing",
  "image-animation",
  "interest-delay",
  "interest-delay-end",
  "interest-delay-start",
  "justify-tracks",
  "link-parameters",
  "masonry-auto-flow",
  "overflow-clip-box",
  "path-length",
  "pointer-timeline",
  "pointer-timeline-axis",
  "pointer-timeline-name",
  "row-rule-inset",
  "row-rule-inset-cap",
  "row-rule-inset-cap-end",
  "row-rule-inset-cap-start",
  "row-rule-inset-end",
  "row-rule-inset-junction",
  "row-rule-inset-junction-end",
  "row-rule-inset-junction-start",
  "row-rule-inset-start",
  "row-rule-visibility-items",
  "rule-inset",
  "rule-inset-cap",
  "rule-inset-end",
  "rule-inset-junction",
  "rule-inset-start",
  "rule-overlap",
  "rule-visibility-items",
  "shape-padding",
  "text-decoration-inset",
  "text-fit",
  "timeline-trigger",
  "timeline-trigger-activation-range",
  "timeline-trigger-activation-range-end",
  "timeline-trigger-activation-range-start",
  "timeline-trigger-active-range",
  "timeline-trigger-active-range-end",
  "timeline-trigger-active-range-start",
  "timeline-trigger-exit-range",
  "timeline-trigger-exit-range-end",
  "timeline-trigger-exit-range-start",
  "timeline-trigger-name",
  "timeline-trigger-range",
  "timeline-trigger-range-end",
  "timeline-trigger-range-start",
  "timeline-trigger-source",
  "trigger-scope",
  "view-transition-scope",
  "window-drag",
];

/// Properties in `known-css-properties`, and so known to Stylelint 16, that
/// Stylelint 17 no longer treats as properties: mostly at-rule descriptors
/// such as `src` and `unicode-range`.
static STYLELINT_16_PROPERTIES: &[&str] = &[
  "additive-symbols",
  "ascent-override",
  "azimuth",
  "base-palette",
  "descent-override",
  "fallback",
  "font-display",
  "inherits",
  "initial-value",
  "item-cross",
  "item-direction",
  "item-flow",
  "item-pack",
  "item-track",
  "item-wrap",
  "line-gap-override",
  "marks",
  "max-zoom",
  "min-zoom",
  "negative",
  "orientation",
  "override-colors",
  "pad",
  "page-orientation",
  "prefix",
  "range",
  "size",
  "size-adjust",
  "src",
  "suffix",
  "symbols",
  "syntax",
  "system",
  "types",
  "unicode-range",
  "user-zoom",
  "viewport-fit",
];

// ---------------------------------------------------------------------------
// At-rules
// ---------------------------------------------------------------------------

static KNOWN_AT_RULES: &[&str] = &[
  "charset",
  "color-profile",
  "container",
  "counter-style",
  "document",
  "font-face",
  "font-feature-values",
  "font-palette-values",
  "function",
  "import",
  "keyframes",
  "layer",
  "media",
  "namespace",
  "page",
  "position-try",
  "property",
  "scope",
  "starting-style",
  "supports",
  "view-transition",
  "viewport",
];

// ---------------------------------------------------------------------------
// SCSS / Sass at-rules (sorted)
// ---------------------------------------------------------------------------

static KNOWN_SCSS_AT_RULES: &[&str] = &[
  "at-root", "content", "debug", "each", "else", "else if", "error", "extend", "for", "forward",
  "function", "if", "include", "mixin", "return", "use", "warn", "while",
];

// ---------------------------------------------------------------------------
// Less at-rules (sorted)
// ---------------------------------------------------------------------------

static KNOWN_LESS_AT_RULES: &[&str] = &["detached-ruleset", "plugin"];

// ---------------------------------------------------------------------------
// Pseudo-classes (without the leading colon)
// ---------------------------------------------------------------------------

static KNOWN_PSEUDO_CLASSES: &[&str] = &[
  "active",
  "active-view-transition",
  "active-view-transition-type",
  "any-link",
  "autofill",
  "buffering",
  "checked",
  "current",
  "default",
  "defined",
  "dir",
  "disabled",
  "empty",
  "enabled",
  "first-child",
  "first-of-type",
  "focus",
  "focus-visible",
  "focus-within",
  "fullscreen",
  "future",
  "has",
  "has-slotted",
  "heading",
  "host",
  "host-context",
  "hover",
  "in-range",
  "indeterminate",
  "invalid",
  "is",
  "lang",
  "last-child",
  "last-of-type",
  "left",
  "link",
  "local-link",
  "low-value",
  "matches",
  "modal",
  "muted",
  "not",
  "nth-child",
  "nth-last-child",
  "nth-last-of-type",
  "nth-of-type",
  "only-child",
  "only-of-type",
  "open",
  "optional",
  "out-of-range",
  "past",
  "paused",
  "picture-in-picture",
  "placeholder-shown",
  "playing",
  "popover-open",
  "read-only",
  "read-write",
  "required",
  "right",
  "root",
  "scope",
  "seeking",
  "stalled",
  "state",
  "suboptimal-value",
  "target",
  "unchecked",
  "user-error",
  "user-invalid",
  "user-valid",
  "valid",
  "visited",
  "volume-locked",
  "where",
];

// ---------------------------------------------------------------------------
// Pseudo-elements (without the leading ::)
// ---------------------------------------------------------------------------

static KNOWN_PSEUDO_ELEMENTS: &[&str] = &[
  "after",
  "backdrop",
  "before",
  "content",
  "cue",
  "details-content",
  "file-selector-button",
  "first-letter",
  "first-line",
  "grammar-error",
  "highlight",
  "marker",
  "part",
  "placeholder",
  "selection",
  "slotted",
  "spelling-error",
  "target-text",
  "view-transition",
  "view-transition-group",
  "view-transition-image-pair",
  "view-transition-new",
  "view-transition-old",
];

// ---------------------------------------------------------------------------
// CSS Units (all lowercase, sorted)
// ---------------------------------------------------------------------------

static KNOWN_UNITS: &[&str] = &[
  "%", "cap", "ch", "cm", "cqb", "cqh", "cqi", "cqmax", "cqmin", "cqw", "deg", "dpcm", "dpi",
  "dppx", "dvb", "dvh", "dvi", "dvmax", "dvmin", "dvw", "em", "ex", "fr", "grad", "hz", "ic", "in",
  "khz", "lh", "lvb", "lvh", "lvi", "lvmax", "lvmin", "lvw", "mm", "ms", "pc", "pt", "px", "q",
  "rad", "rcap", "rch", "rem", "rex", "ric", "rlh", "s", "svb", "svh", "svi", "svmax", "svmin",
  "svw", "turn", "vb", "vh", "vi", "vmax", "vmin", "vw", "x",
];

// ---------------------------------------------------------------------------
// CSS Media Features (sorted)
// ---------------------------------------------------------------------------

static KNOWN_MEDIA_FEATURES: &[&str] = &[
  "any-hover",
  "any-pointer",
  "aspect-ratio",
  "color",
  "color-gamut",
  "color-index",
  "device-aspect-ratio",
  "device-height",
  "device-width",
  "display-mode",
  "dynamic-range",
  "environment-blending",
  "forced-colors",
  "grid",
  "height",
  "horizontal-viewport-segments",
  "hover",
  "inverted-colors",
  "max-aspect-ratio",
  "max-color",
  "max-color-index",
  "max-device-aspect-ratio",
  "max-device-height",
  "max-device-width",
  "max-height",
  "max-monochrome",
  "max-resolution",
  "max-width",
  "min-aspect-ratio",
  "min-color",
  "min-color-index",
  "min-device-aspect-ratio",
  "min-device-height",
  "min-device-width",
  "min-height",
  "min-monochrome",
  "min-resolution",
  "min-width",
  "monochrome",
  "nav-controls",
  "orientation",
  "overflow-block",
  "overflow-inline",
  "pointer",
  "prefers-color-scheme",
  "prefers-contrast",
  "prefers-reduced-data",
  "prefers-reduced-motion",
  "prefers-reduced-transparency",
  "resolution",
  "scan",
  "scripting",
  "update",
  "vertical-viewport-segments",
  "video-color-gamut",
  "video-dynamic-range",
  "width",
];

// ---------------------------------------------------------------------------
// HTML Elements (sorted)
// ---------------------------------------------------------------------------

static KNOWN_HTML_ELEMENTS: &[&str] = &[
  "a",
  "abbr",
  "acronym",
  "address",
  "animate",
  "animatemotion",
  "animatetransform",
  "annotation",
  "annotation-xml",
  "applet",
  "area",
  "article",
  "aside",
  "audio",
  "b",
  "base",
  "basefont",
  "bdi",
  "bdo",
  "big",
  "blockquote",
  "body",
  "br",
  "button",
  "canvas",
  "caption",
  "center",
  "circle",
  "cite",
  "clippath",
  "code",
  "col",
  "colgroup",
  "data",
  "datalist",
  "dd",
  "defs",
  "del",
  "desc",
  "details",
  "dfn",
  "dialog",
  "div",
  "dl",
  "dt",
  "ellipse",
  "em",
  "embed",
  "feblend",
  "fecolormatrix",
  "fecomponenttransfer",
  "fecomposite",
  "feflood",
  "fefunca",
  "fefuncb",
  "fefuncg",
  "fefuncr",
  "fegaussianblur",
  "femerge",
  "femergenode",
  "feoffset",
  "fieldset",
  "figcaption",
  "figure",
  "filter",
  "font",
  "footer",
  "foreignobject",
  "form",
  "g",
  "h1",
  "h2",
  "h3",
  "h4",
  "h5",
  "h6",
  "head",
  "header",
  "hgroup",
  "hr",
  "html",
  "i",
  "iframe",
  "image",
  "img",
  "input",
  "ins",
  "kbd",
  "label",
  "legend",
  "li",
  "line",
  "lineargradient",
  "link",
  "maction",
  "main",
  "map",
  "mark",
  "marker",
  "mask",
  "math",
  "menclose",
  "menu",
  "merror",
  "meta",
  "metadata",
  "meter",
  "mfenced",
  "mfrac",
  "mi",
  "mmultiscripts",
  "mn",
  "mo",
  "mover",
  "mpadded",
  "mphantom",
  "mprescripts",
  "mroot",
  "mrow",
  "ms",
  "mspace",
  "msqrt",
  "mstyle",
  "msub",
  "msubsup",
  "msup",
  "mtable",
  "mtd",
  "mtext",
  "mtr",
  "munder",
  "munderover",
  "nav",
  "none",
  "noscript",
  "object",
  "ol",
  "optgroup",
  "option",
  "output",
  "p",
  "param",
  "path",
  "pattern",
  "picture",
  "polygon",
  "polyline",
  "pre",
  "progress",
  "q",
  "radialgradient",
  "rect",
  "rp",
  "rt",
  "ruby",
  "s",
  "samp",
  "script",
  "search",
  "section",
  "select",
  "semantics",
  "set",
  "slot",
  "small",
  "source",
  "span",
  "stop",
  "strike",
  "strong",
  "style",
  "sub",
  "summary",
  "sup",
  "svg",
  "switch",
  "symbol",
  "table",
  "tbody",
  "td",
  "template",
  "text",
  "textarea",
  "textpath",
  "tfoot",
  "th",
  "thead",
  "time",
  "title",
  "tr",
  "track",
  "tspan",
  "tt",
  "u",
  "ul",
  "use",
  "var",
  "video",
  "wbr",
];

/// HTML elements Stylelint knows about that are not yet in the standard set.
static EXPERIMENTAL_HTML_ELEMENTS: &[&str] = &[
  "fencedframe",
  "geolocation",
  "install",
  "listbox",
  "model",
  "portal",
  "selectedcontent",
  "selectlist",
  "usermedia",
];

#[cfg(test)]
mod tests {
  use super::*;

  #[test]
  fn known_properties() {
    assert!(is_known_property("color"));
    assert!(is_known_property("Color")); // case-insensitive
    assert!(is_known_property("display"));
    assert!(is_known_property("flex-direction"));
    assert!(!is_known_property("colr"));
    assert!(!is_known_property("fake-property"));
  }

  #[test]
  fn known_properties_follow_the_stylelint_version() {
    for major in [16, 17] {
      // Anchor positioning and SVG properties both versions know.
      for name in [
        "anchor-name",
        "position-anchor",
        "position-try-fallbacks",
        "vector-effect",
      ] {
        assert!(is_known_property_for(name, major), "{name} in {major}");
      }
    }
    assert!(is_known_property_for("corner-shape", 17));
    assert!(!is_known_property_for("corner-shape", 16));
    assert!(is_known_property_for("unicode-range", 16));
    assert!(!is_known_property_for("unicode-range", 17));
  }

  #[test]
  fn known_at_rules() {
    assert!(is_known_at_rule("media"));
    assert!(is_known_at_rule("keyframes"));
    assert!(is_known_at_rule("import"));
    assert!(!is_known_at_rule("tailwind"));
  }

  #[test]
  fn known_at_rules_for_scss() {
    assert!(is_known_at_rule_for_syntax("media", Syntax::Scss));
    assert!(is_known_at_rule_for_syntax("mixin", Syntax::Scss));
    assert!(is_known_at_rule_for_syntax("include", Syntax::Scss));
    assert!(is_known_at_rule_for_syntax("if", Syntax::Scss));
    assert!(is_known_at_rule_for_syntax("each", Syntax::Scss));
    assert!(is_known_at_rule_for_syntax("use", Syntax::Scss));
    assert!(is_known_at_rule_for_syntax("forward", Syntax::Scss));
    assert!(is_known_at_rule_for_syntax("at-root", Syntax::Scss));
    assert!(!is_known_at_rule_for_syntax("mixin", Syntax::Css));
    assert!(!is_known_at_rule_for_syntax("plugin", Syntax::Scss));
  }

  #[test]
  fn known_at_rules_for_less() {
    assert!(is_known_at_rule_for_syntax("media", Syntax::Less));
    assert!(is_known_at_rule_for_syntax("plugin", Syntax::Less));
    assert!(is_known_at_rule_for_syntax(
      "detached-ruleset",
      Syntax::Less
    ));
    assert!(!is_known_at_rule_for_syntax("plugin", Syntax::Css));
    assert!(!is_known_at_rule_for_syntax("mixin", Syntax::Less));
  }

  #[test]
  fn known_pseudo_classes() {
    assert!(is_known_pseudo_class("hover"));
    assert!(is_known_pseudo_class("focus"));
    assert!(is_known_pseudo_class("nth-child"));
    assert!(!is_known_pseudo_class("hoverr"));
  }

  #[test]
  fn known_pseudo_elements() {
    assert!(is_known_pseudo_element("before"));
    assert!(is_known_pseudo_element("after"));
    assert!(is_known_pseudo_element("placeholder"));
    assert!(!is_known_pseudo_element("beforre"));
  }

  #[test]
  fn known_units() {
    assert!(is_known_unit("px"));
    assert!(is_known_unit("rem"));
    assert!(is_known_unit("em"));
    assert!(is_known_unit("%"));
    assert!(!is_known_unit("xyz"));
  }

  #[test]
  fn known_media_features() {
    assert!(is_known_media_feature("width"));
    assert!(is_known_media_feature("min-width"));
    assert!(is_known_media_feature("hover"));
    assert!(is_known_media_feature("prefers-color-scheme"));
    assert!(!is_known_media_feature("fake-feature"));
  }

  #[test]
  fn known_html_elements() {
    assert!(is_known_html_element("div"));
    assert!(is_known_html_element("span"));
    assert!(is_known_html_element("a"));
    assert!(is_known_html_element("section"));
    assert!(!is_known_html_element("fakeelement"));
  }

  #[test]
  fn known_mathml_elements() {
    // MathML 4 tags added for Stylelint v17 compatibility
    assert!(is_known_html_element("math"));
    assert!(is_known_html_element("annotation"));
    assert!(is_known_html_element("annotation-xml"));
    assert!(is_known_html_element("maction"));
    assert!(is_known_html_element("menclose"));
    assert!(is_known_html_element("merror"));
    assert!(is_known_html_element("mfenced"));
    assert!(is_known_html_element("mfrac"));
    assert!(is_known_html_element("mi"));
    assert!(is_known_html_element("mmultiscripts"));
    assert!(is_known_html_element("mn"));
    assert!(is_known_html_element("mo"));
    assert!(is_known_html_element("mover"));
    assert!(is_known_html_element("mpadded"));
    assert!(is_known_html_element("mphantom"));
    assert!(is_known_html_element("mprescripts"));
    assert!(is_known_html_element("mroot"));
    assert!(is_known_html_element("mrow"));
    assert!(is_known_html_element("ms"));
    assert!(is_known_html_element("mspace"));
    assert!(is_known_html_element("msqrt"));
    assert!(is_known_html_element("mstyle"));
    assert!(is_known_html_element("msub"));
    assert!(is_known_html_element("msup"));
    assert!(is_known_html_element("msubsup"));
    assert!(is_known_html_element("mtable"));
    assert!(is_known_html_element("mtd"));
    assert!(is_known_html_element("mtext"));
    assert!(is_known_html_element("mtr"));
    assert!(is_known_html_element("munder"));
    assert!(is_known_html_element("munderover"));
    assert!(is_known_html_element("none"));
    assert!(is_known_html_element("semantics"));
  }

  #[test]
  fn arrays_are_sorted() {
    fn assert_sorted(arr: &[&str], name: &str) {
      for window in arr.windows(2) {
        assert!(
          window[0] < window[1],
          "{name}: '{0}' should come before '{1}'",
          window[0],
          window[1],
        );
      }
    }
    assert_sorted(KNOWN_PROPERTIES, "KNOWN_PROPERTIES");
    assert_sorted(STYLELINT_17_PROPERTIES, "STYLELINT_17_PROPERTIES");
    assert_sorted(STYLELINT_16_PROPERTIES, "STYLELINT_16_PROPERTIES");
    assert_sorted(KNOWN_AT_RULES, "KNOWN_AT_RULES");
    assert_sorted(KNOWN_SCSS_AT_RULES, "KNOWN_SCSS_AT_RULES");
    assert_sorted(KNOWN_LESS_AT_RULES, "KNOWN_LESS_AT_RULES");
    assert_sorted(KNOWN_PSEUDO_CLASSES, "KNOWN_PSEUDO_CLASSES");
    assert_sorted(KNOWN_PSEUDO_ELEMENTS, "KNOWN_PSEUDO_ELEMENTS");
    assert_sorted(KNOWN_UNITS, "KNOWN_UNITS");
    assert_sorted(KNOWN_MEDIA_FEATURES, "KNOWN_MEDIA_FEATURES");
    assert_sorted(KNOWN_HTML_ELEMENTS, "KNOWN_HTML_ELEMENTS");
    assert_sorted(EXPERIMENTAL_HTML_ELEMENTS, "EXPERIMENTAL_HTML_ELEMENTS");
  }
}
